services:
  rumbo:
    build: .
    image: rumbo:latest
    container_name: rumbo
    restart: unless-stopped
    ports:
      - "8765:8765"
    volumes:
      - ./mis_datos:/app/mis_datos
    environment:
      - TZ=Europe/Madrid
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /app/app
        - action: rebuild
          path: ./requirements.txt
        - action: rebuild
          path: ./Dockerfile
x-casaos:
  title:
    es_es: Rumbo
  icon: https://github.com/JonAnderPerez/rumbo/raw/main/docs/logo/rumbo-icono.png
  port_map: "8765"
  index: /
